In [42]:
import pandas as pd
import numpy as np

In [43]:
data=r"C:\Users\Mahakaal\CreditPulse\data\raw\credit_score.csv"
df=pd.read_csv(data)

In [44]:
df.head().T

,0,1,2,3,4
Unnamed: 0,1.000000,2.000000,3.000000,4.00000,5.000000
SeriousDlqin2yrs,1.000000,0.000000,0.000000,0.00000,0.000000
RevolvingUtilizationOfUnsecuredLines,0.766127,0.957151,0.658180,0.23381,0.907239
age,45.000000,40.000000,38.000000,30.00000,49.000000
NumberOfTime30-59DaysPastDueNotWorse,2.000000,0.000000,1.000000,0.00000,1.000000
DebtRatio,0.802982,0.121876,0.085113,0.03605,0.024926
MonthlyIncome,9120.000000,2600.000000,3042.000000,3300.00000,63588.000000
NumberOfOpenCreditLinesAndLoans,13.000000,4.000000,2.000000,5.00000,7.000000
NumberOfTimes90DaysLate,0.000000,0.000000,1.000000,0.00000,0.000000
NumberRealEstateLoansOrLines,6.000000,0.000000,0.000000,0.00000,1.000000
NumberOfTime60-89DaysPastDueNotWorse,0.000000,0.000000,0.000000,0.00000,0.000000
NumberOfDependents,2.000000,1.000000,0.000000,0.00000,0.000000

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [46]:
df=df.drop(columns=['Unnamed: 0'])

In [47]:
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.head().T

,0,1,2,3,4
seriousdlqin2yrs,1.000000,0.000000,0.000000,0.00000,0.000000
revolvingutilizationofunsecuredlines,0.766127,0.957151,0.658180,0.23381,0.907239
age,45.000000,40.000000,38.000000,30.00000,49.000000
numberoftime30-59dayspastduenotworse,2.000000,0.000000,1.000000,0.00000,1.000000
debtratio,0.802982,0.121876,0.085113,0.03605,0.024926
monthlyincome,9120.000000,2600.000000,3042.000000,3300.00000,63588.000000
numberofopencreditlinesandloans,13.000000,4.000000,2.000000,5.00000,7.000000
numberoftimes90dayslate,0.000000,0.000000,1.000000,0.00000,0.000000
numberrealestateloansorlines,6.000000,0.000000,0.000000,0.00000,1.000000
numberoftime60-89dayspastduenotworse,0.000000,0.000000,0.000000,0.00000,0.000000
numberofdependents,2.000000,1.000000,0.000000,0.00000,0.000000

In [48]:
df.isnull().mean()*100

seriousdlqin2yrs                         0.000000
revolvingutilizationofunsecuredlines     0.000000
age                                      0.000000
numberoftime30-59dayspastduenotworse     0.000000
debtratio                                0.000000
monthlyincome                           19.820667
numberofopencreditlinesandloans          0.000000
numberoftimes90dayslate                  0.000000
numberrealestateloansorlines             0.000000
numberoftime60-89dayspastduenotworse     0.000000
numberofdependents                       2.616000
dtype: float64

In [49]:
monthlyincome_median = df['monthlyincome'].median()
df['monthlyincome'] = df['monthlyincome'].fillna(monthlyincome_median)

numberofdependents_median = df['numberofdependents'].median()
df['numberofdependents'] = df['numberofdependents'].fillna(numberofdependents_median)

In [51]:
df.head().T

,0,1,2,3,4
seriousdlqin2yrs,1.000000,0.000000,0.000000,0.00000,0.000000
revolvingutilizationofunsecuredlines,0.766127,0.957151,0.658180,0.23381,0.907239
age,45.000000,40.000000,38.000000,30.00000,49.000000
numberoftime30-59dayspastduenotworse,2.000000,0.000000,1.000000,0.00000,1.000000
debtratio,0.802982,0.121876,0.085113,0.03605,0.024926
monthlyincome,9120.000000,2600.000000,3042.000000,3300.00000,63588.000000
numberofopencreditlinesandloans,13.000000,4.000000,2.000000,5.00000,7.000000
numberoftimes90dayslate,0.000000,0.000000,1.000000,0.00000,0.000000
numberrealestateloansorlines,6.000000,0.000000,0.000000,0.00000,1.000000
numberoftime60-89dayspastduenotworse,0.000000,0.000000,0.000000,0.00000,0.000000
numberofdependents,2.000000,1.000000,0.000000,0.00000,0.000000

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 11 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   seriousdlqin2yrs                      150000 non-null  int64
 1   revolvingutilizationofunsecuredlines  150000 non-null  float64
 2   age                                   150000 non-null  int64
 3   numberoftime30-59dayspastduenotworse  150000 non-null  int64
 4   debtratio                             150000 non-null  float64
 5   monthlyincome                         150000 non-null  float64
 6   numberofopencreditlinesandloans       150000 non-null  int64
 7   numberoftimes90dayslate               150000 non-null  int64
 8   numberrealestateloansorlines          150000 non-null  int64
 9   numberoftime60-89dayspastduenotworse  150000 non-null  int64
 10  numberofdependents                    150000 non-null  float64
dtypes: float64(4), int64(7)
memory usage: 12.6 MB

In [50]:
df.to_csv(r"C:\Users\Mahakaal\CreditPulse\data\processed\credit_score_clean.csv", index=False)